### ISSUE TITLE
Has no exported member 'wait'

### ISSUE THREAD

**Issue by samuelslf** [bergben/ng2-page-transition#10]
Helo, i downloaded the demo through the link https://github.com/matsko/ng4-animations-preview, but I am not able to compile when i compile it is printing the following error 'has no exported member 'wait '.". In the animation library.

**Comment by bergben** [comment]
Hi @SamuelSlf , the ng4-animations don't have anything to do with ng2-page-transition. You have to create an Issue at the angular project. I don't really know about what could cause that issue either.

**Comment by samuelslf** [comment]
Thanks @bergben !!!
