### ISSUE TITLE
zone.js:642 Unhandled Promise rejection: Cannot read property 'play' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'play' of undefined

### ISSUE THREAD

**Issue by preservance717** [bergben/ng2-page-transition#11]
zone.js:642 Unhandled Promise rejection: Cannot read property 'play' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'play' of undefined.[
![problem](https://user-images.githubusercontent.com/18299850/28005219-0477df16-657c-11e7-95ce-094596a06237.png)
](url)
That‘s why?

**Comment by bergben** [comment]
Hey there @preservance717 ,

could it be that you are using Angular 4.x? This package only works for Angular 2.x.
Another idea is that you may be using a custom animation, which is invalid and doesn't work...

**Comment by preservance717** [comment]
yes,i am using Angular4.x.
yes, i am using a custom animation-pagination.
but i don't know the reason that it doesn't work.

**Comment by bergben** [comment]
If you are using Angular 4.x it's all clear. This package does not support Angular 4.x as Angular 4.x allows route transitions way cleaner and smoother than this package does.
Please refer to 
the Readme: https://github.com/bergben/ng2-page-transition#works-for-angular-2x-only-angular-42-supports-route-transitions-built-in 
or for more detailed information: https://github.com/bergben/ng2-page-transition/issues/8 

I hope this helps :)
