### ISSUE TITLE
Double Blink in firefox

### ISSUE THREAD

**Issue by miteshyugtia** [bergben/ng2-page-transition#12]
I have used ng2-page-transition in my code.
When I do page refresh in firefox it's blin for two times.
Any one have solutions,Please let me know.
Thanks

**Comment by bergben** [comment]
Hi @miteshyugtia,

are you using the default animation? Unfortunately `ng2-page-transition` generally does not work that smooth since the possibilities to create / handle animations were relatively restricted for Angular 2.x :(
