### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by shan75** [bergben/ng2-page-transition#13]
Hi

I am fairly new to Angular 2 and I have a latest version angular project. I am very much interested in this transition animation. I have installed your component. But it is not working

I get errors like style, transition not supported in angular core.

Have you upgraded to latest version of angular??

Please let me know

Thanks

**Comment by bergben** [comment]
Please refer to the first lines in the ReadMe: https://github.com/bergben/ng2-page-transition#works-for-angular-2x-only-angular-42-supports-route-transitions-built-in
