### ISSUE TITLE
Get ugly appearance of transitioned page and then rapid fade out and slow fade in

### ISSUE THREAD

**Issue by FastAndFluid** [bergben/ng2-page-transition#3]
Just installed this with Angular 2.4.5  Very simple installation but the end-results look worse than not having any animation. The new ng-outlet page appears and then gives an ugly "blink". What seems to be happening it it appears just as it would with no animation and then quickly fades to 100% opacity and then slowly fades back in again.

**Comment by bergben** [comment]
This should be fixed now.

**Comment by FastAndFluid** [comment]
Seems to have introduced a new issue that causes Webpack to fail any compilations that use it with: "ERROR in [default] <omitted for clarity>\node_modules\ng2-page-transition\src\ng2-page-transition.component.d.ts:1:0
Cannot find type definition file for 'core-js'.
webpack: Failed to compile."

**Comment by bergben** [comment]
@FastAndFluid  thanks for reporting back. Could you check if it works now with 0.2.5?

**Comment by FastAndFluid** [comment]
That works perfectly :-)  Many thanks! Just in time for a screen capture demo of an app I have to do for a client.
