### ISSUE TITLE
When guard is in place page is displayed with incorrect transition state

### ISSUE THREAD

**Issue by FastAndFluid** [bergben/ng2-page-transition#4]
When I navigate to a page that has a guard on it (eg if the user is not logged in) the navigation locks on the original page in its end transition state so eg if I transition from page 1 to page 2 and page 2 has a canActivate guard that returns false the original page is displayed but with an opacity that makes it barely legible.  Can you advise how to best deal with this scenario, and when you have a demo perhaps demonstrate it?

**Comment by bergben** [comment]
This should be fixed with 0.2.6 by adding NavigationCancel as a trigger too, thanks for reporting the issue!
