### ISSUE TITLE
v0.2.7 breaks with missing module because no src folder and contents

### ISSUE THREAD

**Issue by FastAndFluid** [bergben/ng2-page-transition#5]
A co-worker just complained the build was broken when installing using "^0.2.6" because the src folder appears to be missing when 0.2.7 is installed. Changing our package.json file to hard-coding the version at 0.2.6 fixed the issue but looks like 0.2.7 is broken?

**Comment by bergben** [comment]
Thanks for reporting that! 

Version 1.0.4 should fix this. Careful though, version 1.0.3 https://github.com/bergben/ng2-page-transition/releases/tag/1.0.3 turns this project into a module. (It's a matter of seconds to change the import).
