### ISSUE TITLE
disabling transition on aux routes

### ISSUE THREAD

**Issue by jmw5598** [bergben/ng2-page-transition#9]
Is it possible to disable transitions on aux routes.  Say I have these routes

/settings
/settings/(aux:user)
/settings/(aux:other)

I only want the transition to trigger on the first loading of settings and not to trigger during aux route changes.  The aux router-outlet is a sub navigation of the settings page (settings being loaded in the primary router-outlet)

Thanks

Jason

**Comment by bergben** [comment]
I will look into it ASAP

**Comment by bergben** [comment]
I have just realeased version 1.1.0 which adds `ignoreOnRoutes`: https://github.com/bergben/ng2-page-transition#ignoreonroutes
You could then simply ignore the aux routes 

```
<ng2-page-transition [ignoreOnRoutes]="['aux:']">
    <router-outlet></router-outlet>
    Some other content
</ng2-page-transition>
```

I haven't tested this so it would be great if you could report back here @jmw5598 

Thanks!

**Comment by jmw5598** [comment]
@bergben 
Just wanted to report back to you.  This is working perfect for me.

Thanks again.

**Comment by bergben** [comment]
Glad to hear that @jmw5598 :)
